# Read the Docs 配置文件
# 详细文档: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# 构建环境配置
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# 使用 MkDocs 构建文档
mkdocs:
  configuration: mkdocs.yml

# Python 依赖
python:
  install:
    - requirements: requirements.txt
